path: C:\Users\Miilee\Documents\Test Images\FlagDetect.v1i.yolov8
train: train\images
val: valid\images

nc: 12
names: ['Bolivia flag', 'Chile flag', 'Ecuador flag', 'Guyana flag', 'Peru flag', 'Uruguay flag', 'Venezuela flag', 'argentina flag', 'brazil flag', 'colombia flag', 'paraguay flag', 'suriname flag']
